In Memory App
Pukkah/flight-planner pull request #1
Opened 2022-04-20 11:31 UTC by Pukkah

2022-04-29 11:03 UTC, NilsKula requested changes
domain būs hierarhija augšpusē n to ariport un flight mierīgi var likt vienā
```
domain
-airport
-flight

2022-04-29 11:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/controller/AdminFlightController.java
> +    public synchronized Flight addFlight(@Valid @RequestBody Flight flight) {
šeit labāk izveidot papildus API objektu `addFlightRequest` piemēram, tad no kura tad tālāk taisi `new Flight`

2022-04-29 11:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/domain/Flight.java
> +    @EqualsAndHashCode.Exclude
why this? :thinking:

2022-04-29 12:08 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightService.java
> +        if (flight.getFrom().equals(flight.getTo())) {
un šadas vietas patiesība būtu labāk iznest uz `Flight` class `isValidRoute()` un arī citās vietas, `validTime`, `flightMatches()` utt

2022-04-29 16:13 UTC, Pukkah commented on src/main/java/io/codelex/flightplanner/flight/domain/Flight.java
> +    @EqualsAndHashCode.Exclude
Lai salīdzinot Flight ar citu Flight izmantojot equals() izgnorētu ID.

2022-05-01 12:38 UTC, NilsKula approved these changes

2022-05-01 12:56 UTC, merged